export const SURVEY_CATEGORIES = [
  {
    id: "data_infrastructure",
    label: "Data Infrastructure",
    description: "Assess your organization's data collection, storage, quality, and governance capabilities",
    icon: "Database",
    questions: [
      {
        id: "di_01",
        text: "How would you rate the quality and completeness of your organization's data assets?",
        type: "scale" as const,
        weight: 1.5,
        helpText: "Consider accuracy, completeness, timeliness, and consistency of data across systems",
        options: [
          { value: 1, label: "Very Poor - Data is fragmented, siloed, and unreliable" },
          { value: 2, label: "Poor - Some data exists but quality is inconsistent" },
          { value: 3, label: "Moderate - Data is reasonably clean but gaps exist" },
          { value: 4, label: "Good - High-quality data with minor issues" },
          { value: 5, label: "Excellent - Clean, complete, well-governed data pipelines" },
        ],
      },
      {
        id: "di_02",
        text: "How mature is your organization's data storage and management infrastructure?",
        type: "scale" as const,
        weight: 1.2,
        helpText: "Consider data warehouses, data lakes, cloud storage, and data pipelines",
        options: [
          { value: 1, label: "No formal data infrastructure - spreadsheets/local files" },
          { value: 2, label: "Basic databases with limited integration" },
          { value: 3, label: "Centralized data warehouse with some cloud adoption" },
          { value: 4, label: "Modern cloud data platform with data lake" },
          { value: 5, label: "Enterprise-grade real-time data platform fully cloud-native" },
        ],
      },
      {
        id: "di_03",
        text: "To what extent does your organization practice formal data governance?",
        type: "scale" as const,
        weight: 1.0,
        helpText: "Consider data cataloging, lineage, ownership policies, and access controls",
        options: [
          { value: 1, label: "No data governance practices in place" },
          { value: 2, label: "Ad-hoc data management with no formal policies" },
          { value: 3, label: "Some data governance policies defined but inconsistently applied" },
          { value: 4, label: "Formal data governance with ownership and quality standards" },
          { value: 5, label: "Enterprise data governance with automated enforcement and cataloging" },
        ],
      },
      {
        id: "di_04",
        text: "How well does your organization collect and utilize real-time or near-real-time data?",
        type: "scale" as const,
        weight: 1.0,
        helpText: "Consider streaming pipelines, real-time analytics, and event-driven architectures",
        options: [
          { value: 1, label: "All data is batch-processed with significant delays" },
          { value: 2, label: "Mostly batch with some near-real-time reporting" },
          { value: 3, label: "Mixed batch and streaming with some real-time dashboards" },
          { value: 4, label: "Significant real-time data capabilities across core systems" },
          { value: 5, label: "Fully real-time event-driven architecture with streaming analytics" },
        ],
      },
    ],
  },
  {
    id: "technology_stack",
    label: "Technology Stack",
    description: "Evaluate the tools, platforms, and technical capabilities your organization uses",
    icon: "Cpu",
    questions: [
      {
        id: "ts_01",
        text: "How would you characterize your organization's overall technology modernization level?",
        type: "scale" as const,
        weight: 1.3,
        helpText: "Consider cloud adoption, API-first architecture, containerization, and microservices",
        options: [
          { value: 1, label: "Legacy systems dominate with minimal modernization" },
          { value: 2, label: "Some modernization but mostly on-premise legacy systems" },
          { value: 3, label: "Hybrid cloud with modernized core systems" },
          { value: 4, label: "Primarily cloud-native with modern DevOps practices" },
          { value: 5, label: "Fully cloud-native with automated CI/CD and platform engineering" },
        ],
      },
      {
        id: "ts_02",
        text: "To what extent does your organization use analytics and BI tools?",
        type: "scale" as const,
        weight: 1.1,
        helpText: "Consider business intelligence, reporting dashboards, and self-service analytics",
        options: [
          { value: 1, label: "No formal analytics tools - manual reporting only" },
          { value: 2, label: "Basic reporting tools used by a few people" },
          { value: 3, label: "BI platform deployed with regular usage across teams" },
          { value: 4, label: "Advanced analytics with self-service BI widely adopted" },
          { value: 5, label: "Embedded analytics and real-time insights across all systems" },
        ],
      },
      {
        id: "ts_03",
        text: "How robust is your organization's MLOps and AI infrastructure?",
        type: "scale" as const,
        weight: 1.4,
        helpText: "Consider ML platforms, model registries, feature stores, and deployment infrastructure",
        options: [
          { value: 1, label: "No MLOps infrastructure - models run locally if at all" },
          { value: 2, label: "Basic model training with manual deployment" },
          { value: 3, label: "Some automated pipelines with staging/production environments" },
          { value: 4, label: "Mature MLOps with automated retraining, monitoring, and governance" },
          { value: 5, label: "Enterprise ML platform with full lifecycle management at scale" },
        ],
      },
    ],
  },
  {
    id: "ai_ml_usage",
    label: "AI/ML Usage",
    description: "Assess the depth and breadth of AI and machine learning adoption in your organization",
    icon: "Brain",
    questions: [
      {
        id: "ai_01",
        text: "How extensively is AI/ML being used in your core business processes?",
        type: "scale" as const,
        weight: 2.0,
        helpText: "Consider the number of use cases, business impact, and integration depth",
        options: [
          { value: 1, label: "No AI/ML use cases deployed in production" },
          { value: 2, label: "1-2 experimental pilots with limited business impact" },
          { value: 3, label: "Several production AI systems in specific domains" },
          { value: 4, label: "AI embedded across multiple business functions with measurable ROI" },
          { value: 5, label: "AI is central to competitive advantage across the entire organization" },
        ],
      },
      {
        id: "ai_02",
        text: "What is the sophistication level of AI/ML models your organization uses?",
        type: "scale" as const,
        weight: 1.5,
        helpText: "Consider the complexity of models used: rule-based, statistical, ML, deep learning, generative AI",
        options: [
          { value: 1, label: "Rule-based automation only - no statistical or ML models" },
          { value: 2, label: "Basic statistical models and simple ML (regression, classification)" },
          { value: 3, label: "Intermediate ML with ensemble methods and neural networks" },
          { value: 4, label: "Advanced deep learning and specialized models in production" },
          { value: 5, label: "Large language models, foundation models, and generative AI at scale" },
        ],
      },
      {
        id: "ai_03",
        text: "How well does your organization measure and track AI model performance over time?",
        type: "scale" as const,
        weight: 1.2,
        helpText: "Consider model monitoring, drift detection, and business outcome tracking",
        options: [
          { value: 1, label: "No monitoring - models run without performance tracking" },
          { value: 2, label: "Ad-hoc spot checks with no systematic monitoring" },
          { value: 3, label: "Regular performance reviews with manual intervention" },
          { value: 4, label: "Automated monitoring with alerts and scheduled retraining" },
          { value: 5, label: "Continuous monitoring with autonomous model management and A/B testing" },
        ],
      },
      {
        id: "ai_04",
        text: "How broadly has your organization adopted Generative AI tools?",
        type: "scale" as const,
        weight: 1.3,
        helpText: "Consider LLM-powered applications, AI assistants, and content generation tools",
        options: [
          { value: 1, label: "No GenAI tools or experimentation" },
          { value: 2, label: "A few employees using consumer GenAI tools informally" },
          { value: 3, label: "Sanctioned GenAI tools for select teams with some productivity gains" },
          { value: 4, label: "GenAI integrated into key workflows with measurable productivity improvement" },
          { value: 5, label: "Custom GenAI applications delivering strategic differentiation" },
        ],
      },
    ],
  },
  {
    id: "workforce_skills",
    label: "Workforce Skills",
    description: "Evaluate AI literacy, talent capabilities, and learning culture across your organization",
    icon: "Users",
    questions: [
      {
        id: "ws_01",
        text: "How would you rate the overall AI literacy across your organization's workforce?",
        type: "scale" as const,
        weight: 1.4,
        helpText: "Consider the proportion of employees who understand AI basics and can work alongside AI systems",
        options: [
          { value: 1, label: "Minimal - Most employees have no AI awareness" },
          { value: 2, label: "Low - A few technical staff have AI knowledge" },
          { value: 3, label: "Moderate - Technical teams are AI-literate; business teams less so" },
          { value: 4, label: "Good - Widespread AI literacy with active upskilling programs" },
          { value: 5, label: "Excellent - AI fluency embedded across all functions and levels" },
        ],
      },
      {
        id: "ws_02",
        text: "How strong is your organization's internal AI/data science talent pool?",
        type: "scale" as const,
        weight: 1.5,
        helpText: "Consider data scientists, ML engineers, AI researchers, and AI product managers",
        options: [
          { value: 1, label: "No dedicated AI/data science talent" },
          { value: 2, label: "1-3 analysts or data scientists with limited ML experience" },
          { value: 3, label: "A small team of data scientists with some ML engineers" },
          { value: 4, label: "A mature data science team with ML engineers and AI product managers" },
          { value: 5, label: "World-class AI research and engineering teams with specialized roles" },
        ],
      },
      {
        id: "ws_03",
        text: "How proactively does your organization invest in AI training and upskilling?",
        type: "scale" as const,
        weight: 1.1,
        helpText: "Consider structured learning programs, certification support, and AI communities of practice",
        options: [
          { value: 1, label: "No AI training programs or budget allocated" },
          { value: 2, label: "Ad-hoc self-directed learning with no organizational support" },
          { value: 3, label: "Some sponsored training programs for technical staff" },
          { value: 4, label: "Structured AI upskilling programs across multiple levels" },
          { value: 5, label: "Continuous AI learning culture with mandatory literacy and advanced tracks" },
        ],
      },
    ],
  },
  {
    id: "leadership_vision",
    label: "Leadership Vision",
    description: "Assess executive commitment, AI strategy clarity, and organizational alignment",
    icon: "Target",
    questions: [
      {
        id: "lv_01",
        text: "How clearly has your organization articulated an AI strategy?",
        type: "scale" as const,
        weight: 1.8,
        helpText: "Consider whether AI strategy is documented, communicated, and linked to business goals",
        options: [
          { value: 1, label: "No AI strategy exists - decisions are ad-hoc" },
          { value: 2, label: "Informal interest in AI but no formal strategy" },
          { value: 3, label: "Draft AI strategy exists but not broadly communicated or funded" },
          { value: 4, label: "Clear AI strategy aligned with business goals with executive sponsorship" },
          { value: 5, label: "AI is a pillar of the corporate strategy with board-level accountability" },
        ],
      },
      {
        id: "lv_02",
        text: "How committed is senior leadership to AI investment and transformation?",
        type: "scale" as const,
        weight: 1.6,
        helpText: "Consider budget commitment, executive ownership, and willingness to change operating models",
        options: [
          { value: 1, label: "Leadership shows little interest or skepticism toward AI" },
          { value: 2, label: "Leadership is curious but cautious with minimal investment" },
          { value: 3, label: "Leadership is supportive with some dedicated AI budget" },
          { value: 4, label: "Strong executive commitment with significant and growing AI investment" },
          { value: 5, label: "AI transformation is a top strategic priority with bold investment mandates" },
        ],
      },
      {
        id: "lv_03",
        text: "How effectively does your organization manage AI change and transformation?",
        type: "scale" as const,
        weight: 1.2,
        helpText: "Consider change management maturity, resistance handling, and cultural alignment",
        options: [
          { value: 1, label: "Significant cultural resistance to technology change" },
          { value: 2, label: "Limited change management with resistance to AI adoption" },
          { value: 3, label: "Structured change management for AI initiatives but gaps remain" },
          { value: 4, label: "Proactive change management with strong organizational buy-in" },
          { value: 5, label: "AI-first culture with change agility as a core competency" },
        ],
      },
    ],
  },
  {
    id: "operational_processes",
    label: "Operational Processes",
    description: "Evaluate automation levels, process efficiency, and operational AI integration",
    icon: "Settings",
    questions: [
      {
        id: "op_01",
        text: "How extensively have you automated repetitive operational tasks?",
        type: "scale" as const,
        weight: 1.4,
        helpText: "Consider RPA, workflow automation, and intelligent process automation",
        options: [
          { value: 1, label: "Mostly manual processes with minimal automation" },
          { value: 2, label: "Some basic automation of isolated tasks" },
          { value: 3, label: "Moderate automation of key operational processes" },
          { value: 4, label: "Broad automation with intelligent workflow orchestration" },
          { value: 5, label: "Highly automated end-to-end operations with AI-driven process optimization" },
        ],
      },
      {
        id: "op_02",
        text: "How data-driven are your organization's core operational decisions?",
        type: "scale" as const,
        weight: 1.6,
        helpText: "Consider whether decisions are based on intuition, reports, analytics, or AI recommendations",
        options: [
          { value: 1, label: "Decisions primarily based on intuition and experience" },
          { value: 2, label: "Some use of historical reports for decision support" },
          { value: 3, label: "Analytics-informed decisions with dashboards and KPIs" },
          { value: 4, label: "Predictive analytics driving most operational decisions" },
          { value: 5, label: "AI-driven autonomous decisions with human oversight on exceptions" },
        ],
      },
      {
        id: "op_03",
        text: "How effectively does your organization use AI for customer-facing operations?",
        type: "scale" as const,
        weight: 1.3,
        helpText: "Consider AI chatbots, recommendation engines, personalization, and customer service automation",
        options: [
          { value: 1, label: "No AI used in customer interactions" },
          { value: 2, label: "Basic chatbots or FAQ automation" },
          { value: 3, label: "AI-powered customer service tools with some personalization" },
          { value: 4, label: "Sophisticated AI driving personalization, recommendations, and support" },
          { value: 5, label: "AI-first customer experience with hyper-personalization at scale" },
        ],
      },
    ],
  },
  {
    id: "governance_ethics",
    label: "Governance & Ethics",
    description: "Assess AI risk management, responsible AI practices, compliance, and oversight frameworks",
    icon: "Shield",
    questions: [
      {
        id: "ge_01",
        text: "How mature is your organization's AI governance framework?",
        type: "scale" as const,
        weight: 1.5,
        helpText: "Consider AI policies, risk committees, model documentation requirements, and oversight structures",
        options: [
          { value: 1, label: "No AI governance policies or oversight structures" },
          { value: 2, label: "Awareness of governance needs but nothing formalized" },
          { value: 3, label: "Basic AI policies exist with limited enforcement" },
          { value: 4, label: "Formal AI governance with risk committee and model documentation" },
          { value: 5, label: "Enterprise AI governance with automated compliance checks and AI ethics board" },
        ],
      },
      {
        id: "ge_02",
        text: "To what extent does your organization practice responsible and ethical AI?",
        type: "scale" as const,
        weight: 1.4,
        helpText: "Consider fairness, bias testing, explainability, transparency, and human oversight",
        options: [
          { value: 1, label: "No consideration of AI ethics or responsible AI practices" },
          { value: 2, label: "Informal awareness of ethics issues with no formal practices" },
          { value: 3, label: "Some bias testing and explainability requirements for key models" },
          { value: 4, label: "Structured responsible AI program with fairness audits and explainability standards" },
          { value: 5, label: "Industry-leading responsible AI with external audits and public accountability" },
        ],
      },
      {
        id: "ge_03",
        text: "How well does your organization manage AI regulatory compliance and data privacy?",
        type: "scale" as const,
        weight: 1.3,
        helpText: "Consider GDPR, CCPA, AI Act compliance, data privacy protections, and regulatory monitoring",
        options: [
          { value: 1, label: "Limited awareness of AI regulations and compliance requirements" },
          { value: 2, label: "Basic data privacy measures but no AI-specific compliance" },
          { value: 3, label: "Compliance with major data privacy regulations; AI regulations emerging" },
          { value: 4, label: "Proactive compliance with all applicable AI and data regulations" },
          { value: 5, label: "Regulatory leadership with dedicated compliance teams and proactive policy engagement" },
        ],
      },
    ],
  },
];

export type SurveyCategory = typeof SURVEY_CATEGORIES[0];
export type SurveyQuestion = SurveyCategory["questions"][0];
